### ISSUE TITLE
Screen is "sunken" on new GLFW

### ISSUE THREAD

**Issue by Eggmanplant** [RSDKModding/RSDKv5-Decompilation#277]
The bottom of the window is "sunken" on GLFW 3.4. Tested on GNOME on Wayland on Void Linux. Screen resolution is 1920x1080@60.00.

https://github.com/user-attachments/assets/7aaf704c-c7c3-4ab4-b7d7-c4a8a12bd80a

**Comment by Mefiresu** [comment]
Works fine for me on KDE Plasma (X11 and Wayland) with the same resolution.
Seems like an issue with the GNOME status bar at the top where it somehow counts towards the max fullscreen size?

**Comment by Eggmanplant** [comment]
Fixed by updating something.

**Comment by MegAmi24** [comment]
Reopening as the issue was not actually solved, see #290 for details

**Comment by HPlinko** [comment]
This is also happening to me on Xfce 4.20 (X11), so not just GNOME.

**Comment by Eggmanplant** [comment]
> This is also happening to me on Xfce 4.20 (X11), so not just GNOME.

Try vulkan.
